name: Publish Docs

on:
  push:
    paths:
      - docs/**
      - osm_login_python/**
      - mkdocs.yml
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@1.4.0
    # with:
    #   doxygen: true
